const {chromium}=require("/home/velzie/src/puter/node_modules/playwright");
const {startBenchServer}=require("./bench-server.cjs");
const sleep=(ms)=>new Promise(r=>setTimeout(r,ms));
const L=(...a)=>console.log(...a);
(async()=>{
 const {server,port}=await startBenchServer(0);
 const b=await chromium.launch({headless:true,args:["--no-sandbox","--disable-dev-shm-usage"]});
 const p=await b.newPage();
 await p.goto("http://127.0.0.1:"+port+"/index.html?mirror=1",{waitUntil:"load",timeout:120000});
 await p.waitForFunction(()=>window.__geckoReady===true,{timeout:150000});
 await p.evaluate((u)=>window.geckoRender(u),"http://127.0.0.1:"+port+"/bench/composedtest.html");
 await sleep(4000);
 const sd=await p.evaluate(()=>((document.getElementById('mirror')||{}).srcdoc||""));
 const dataImgs=(sd.match(/src="data:image\/png/g)||[]).length;
 L("data:image/png count (L,S,CV,F => expect 4):", dataImgs);
 L("has shadow template:", /shadowrootmode/.test(sd), " adopted purple css:", /color:purple/.test(sd));
 L("has iframe srcdoc  :", /<iframe[^>]*srcdoc=/.test(sd));
 await p.screenshot({path:"/tmp/composed.png"});
 L("shot -> /tmp/composed.png");
 await b.close();server.close();process.exit(0);
})().catch(e=>{console.error("fatal",e.message);process.exit(1);});
