const {chromium}=require("/home/velzie/src/puter/node_modules/playwright");
const {startBenchServer}=require("./bench-server.cjs");
const sleep=(ms)=>new Promise(r=>setTimeout(r,ms));
const L=(...a)=>console.log(...a);
(async()=>{
 const {server,port}=await startBenchServer(0);
 const b=await chromium.launch({headless:true,args:["--no-sandbox","--disable-dev-shm-usage"]});
 const p=await b.newPage();
 await p.goto("http://127.0.0.1:"+port+"/index.html?mirror=1",{waitUntil:"load",timeout:120000});
 await p.waitForFunction(()=>window.__geckoReady===true,{timeout:150000});
 await p.evaluate((u)=>window.geckoRender(u),"http://127.0.0.1:"+port+"/bench/shadowframe.html");
 await sleep(3000);
 const sd=await p.evaluate(()=>((document.getElementById('mirror')||{}).srcdoc||""));
 L("has shadow template :", /<template shadowrootmode/.test(sd));
 L("has SHADOW-CONTENT   :", /SHADOW-CONTENT/.test(sd));
 L("has shadow scoped css:", /\.b\{background:purple/.test(sd.replace(/\s/g,'')) || /background:purple/.test(sd));
 L("has iframe srcdoc    :", /<iframe[^>]*srcdoc=/.test(sd));
 L("has IFRAME-CONTENT   :", /IFRAME-CONTENT/.test(sd));
 await p.screenshot({path:"/tmp/shadowframe.png"});
 L("shot -> /tmp/shadowframe.png");
 await b.close();server.close();process.exit(0);
})().catch(e=>{console.error("fatal",e.message);process.exit(1);});
